import turtle
tut = turtle.Screen()
# background color green
tut.bgcolor("green")
# window title Turtle
tut.title("Turtle")
# draw pic
my_turtle = turtle.Turtle()
my_turtle.color("yellow")
my_turtle.forward(100)
my_turtle.left(90)
my_turtle.forward(100)
my_turtle.left(90)
my_turtle.forward(100)
my_turtle.left(90)
my_turtle.forward(100)
my_turtle.backward(100)
my_turtle.left(180)
my_turtle.right(45)
my_turtle.forward(50)
my_turtle.right((45))
my_turtle.forward(100)
my_turtle.right(135)
my_turtle.forward(50)
my_turtle.left(45)
my_turtle.forward(100)
my_turtle.left(135)
my_turtle.forward(50)
my_turtle.left(45)
my_turtle.forward(100)
my_turtle.circle(100)
turtle.exitonclick()